name: Build JAR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build JAR
      run: mvn package

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-java-artifact
        path: target/*.jar
