name: Build JAR

on:
  push:
    branches:
      - main

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 1.4
      uses: actions/setup-java@v1
      with:
        java-version: 1.4

    - name: Build with Ant
      run: ant build

    - name: Archive JAR file
      uses: actions/upload-artifact@v2
      with:
        name: JAR
        path: build/my-project.jar